---
title: "Apache_Log"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Apache2 web server log file

```{r data, include=FALSE}
library(tidyverse)
#Realizamos la carga de datos
data <- read.table("Datos.txt", sep = " ")
#Se realiza una limpieza, filtrando los datos cargados correctamente mediante el caracter - (columna2) seguido inmediatamente de la direccion IP (columna1)
data <- data %>% filter(data$V2 == '-')
#Reporte #1 "Top 10 requested pages"
datos1 <- data %>% group_by(data$V9) %>% summarise(cantidad=n()) %>%
  arrange(desc(cantidad)) %>% top_n(10)

#knitr::kable(datos1, caption = "Top1")

#Tomamos de la columa7 la respuesta de las solicitudes, fraccionandolas en satisfatorias y no satisfactorias, se dejan como lista para modificarlas según se requiera
succesfull =  c(200,206,304,301)
unsuccesfull = c(404,500,403,416)

# Reporte #2 "Percentage of successful requests"
per_succ <- round((data %>% filter(V7 %in% succesfull) %>% count())/nrow(data),4)
per_succ <- per_succ*100

# Reporte #3 "Percentage of unsuccessful requests"
per_unsucc <- round((data %>% filter(V7 %in% unsuccesfull) %>% count())/nrow(data),4)
per_unsucc <- per_unsucc*100

# Reporte #4 "Top 10 unsuccessful page requests"
datos2 <- data %>% filter(data$V7 %in% unsuccesfull) 
datos2 <- datos2 %>% filter(V9 != '-') %>% group_by(V9) %>% 
  summarise(cantidad=n()) %>% arrange(desc(cantidad)) %>% head(10)

# Reporte #5 "The top 10 IPs making the largest number of requests"
ip_req <- data %>% group_by(V1) %>% summarise(Cantidad = n()) %>% 
  arrange(desc(Cantidad)) %>% top_n(10) 

#Documento Readme
README = "Esta aplicación esta basada en el archivo de logs de Apache2 que se encuentra en: https://raw.githubusercontent.com/elastic/examples/master/Common%20Data%20Format
s/apache_logs/apache_logs, se realizó una carga inicial de texto, donde se asume que cada línea en el log es un request a una página, se realiza un separado por columnas mediante el caracter espacio. Se construyeron 5 reportes que pueden ser seleccionados a través de la lista desplegable superior."

```

SELECCION DE REPORTES

```{r pressure, echo=FALSE}
selectInput("Reporte", "Elige el reporte", 
            choices = c("Opciones",
                        "Top 10 requested pages",
                        "Percentage of successful requests",
                        "Percentage of unsuccessful requests",
                        "Top 10 unsuccessful page requests",
                        "The top 10 IPs making the largest number of requests"))
```

RESULTADO

```{r echo=FALSE}
renderTable({
  switch (input$Reporte,
          "Opciones" = README,
          "Top 10 requested pages" = datos1,
          "Percentage of successful requests" = per_succ,
          "Percentage of unsuccessful requests" = per_unsucc,
          "Top 10 unsuccessful page requests" = datos2,
          "The top 10 IPs making the largest number of requests" = ip_req
   )
})
```

