---

metricbeat_v_major: "{{metricbeat_version|regex_replace('^([0-9]+)\\..*$', '\\1')}}"
metricbeat_v_minor: "{{metricbeat_version|regex_replace('^[0-9]+\\.([0-9]+).*$', '\\1')}}"
metricbeat_v_patch: "{{metricbeat_version|regex_replace('^[0-9]+\\.[0-9]+\\.([0-9]+.*)$', '\\1')}}"

metricbeat_repo_version:   "{{metricbeat_v_major}}.{{ ((metricbeat_v_major|int) > 1) | ternary('x', metricbeat_v_minor)}}"

metricbeat_apt_key: https://packages.elastic.co/GPG-KEY-elasticsearch
metricbeat_apt_repository: "https://packages.elastic.co/beats/apt"
metricbeat_baseurl: "https://download.elastic.co/beats/metricbeat"

metricbeat_packages:
  - "metricbeat"

# vi:ts=2:sw=2:et:ft=yaml
